import Head from 'next/head'
import Image from 'next/image'
import { useWallet } from '@0xdeepak/wallets'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { connectors, account } = useWallet()

  function handleConnect(connection) {
    connection.connector.activate();
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Connect your wallet
            <code className={styles.code}>src/pages/index.tsx</code>


          </p>

          {account && <p>
            {account && `Connected to: ${account}`}
          </p>
          }

          {connectors?.map((connector) => {
            return <button key={connector?.type} onClick={() => handleConnect(connector)}>{connector?.getName()}</button>
          })}

        </div>
      </main>
    </>
  )
}
